### PR TITLE
update image Upload issue 

### PR DESCRIPTION
**Pull request by JisanAR03**
the implementation wasn't correct , now it's work fine . now user can upload image . 
@Blue9  please look into it

### CODE REVIEW

**Comment by Blue9** [comment]
Hi @JisanAR03, thanks for the PR. The image upload route currently only supports JPEG images because that's what the iOS client will send. I don't want to support additional formats that aren't necessary. However if you strongly disagree I'm open to hearing your argument.

Also, why explicitly read the first 512 bytes of the file instead of letting `imghdr` handle the file object?

**Comment by JisanAR03** [comment]
> Hi @JisanAR03, thanks for the PR. The image upload route currently only supports JPEG images because that's what the iOS client will send. I don't want to support additional formats that aren't necessary. However if you strongly disagree I'm open to hearing your argument.
> 
> Also, why explicitly read the first 512 bytes of the file instead of letting `imghdr` handle the file object?

about the jpeg stuff. very sorry ,I'm new to ios platform . I'm gonna fix this 

And As for reading the first 512 bytes, I was doing this to make the detection and file size checks more efficient, without reading the entire file upfront. However, you're right that imghdr can handle the file object, so I'll modify the PR to leverage imghdr directly without manually reading the bytes.

**Comment by Blue9** [comment]
`imghdr` will only read the first 32 bytes instead of the entire file ([see implementation](https://github.com/python/cpython/blob/3.12/Lib/imghdr.py#L26)).

One thing to note is that [imghdr is deprecated](https://docs.python.org/3/library/imghdr.html), so if we ever want to upgrade to Python 3.13 we'll have to move off of it. Might be something we want to consider now or wait until later. I don't feel too strongly here, but ideally we avoid extra dependencies if possible.

**Comment by JisanAR03** [comment]
@Blue9 Reading the only first 32 bytes is good, I think . Should I make one more commit then you can decide.

**Comment by JisanAR03** [comment]
@Blue9 can you check the latest commit please

**Comment by ramipellumbi** [comment]
> Apologies for the delay @JisanAR03—I was out of town. Looking back on this, I think this PR is unnecessary as `imghdr.what()` will read the first 32 bytes by default, so we don't need to manually read the first 32 bytes. As for using `file.file.seek(0, 2)`, that doesn't work because UploadFile's implementation of `seek()` doesn't support a second argument ([docs](https://fastapi.tiangolo.com/tutorial/request-files/#uploadfile)). This is because we don't have access to the full file as it is not fully received by the server yet (and we don't want to read all of it into memory in the case it is too large). So I'd prefer to stick to the current implementation for now. Let me know what you think.

`imghdr` is also deprecated starting in Python 3.13 -- so if done at all maybe should use another package

**Comment by JisanAR03** [comment]
ok

**Pull request closed without merging**
